language: d
sudo: false

install:
  - curl -fsSLO https://raw.githubusercontent.com/D-Programming-Language/tools/v2.068.2/rdmd.d
  - ${DMD} rdmd.d
  - mv rdmd $(dirname $(which ${DMD}))

d:
    - dmd
    - dmd-2.066.1
    - ldc
    - gdc
