language: d
script: "./travis.sh"
sudo: required 
dist: trusty

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cairo gtk+3; fi

matrix:
  include:
  - d: dmd
    os: linux
    env:
      secure: erukIkEkAI4JeWhvejnTYzZruURBf4dvqXQQm8NK7HOy1Kk28HYMezhVuyNDy7xF6C8vbd8lpY73b1OvwgPDsWJKxxvtcZo8cTYGiNvXGN1Elc0dKvvqf3u7PhMhy/hjnmI22qldp8RemgsoNWcYPtZSHqp9oY63NQXT55YLpUU=
  - d: ldc
    os: linux
  - d: dmd
    os: osx 
