language: d
script: "./travis.sh"
sudo: required
dist: trusty
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cairo gtk+3; fi
matrix:
  include:
  - d: dmd
    os: linux
    env:
      secure: erukIkEkAI4JeWhvejnTYzZruURBf4dvqXQQm8NK7HOy1Kk28HYMezhVuyNDy7xF6C8vbd8lpY73b1OvwgPDsWJKxxvtcZo8cTYGiNvXGN1Elc0dKvvqf3u7PhMhy/hjnmI22qldp8RemgsoNWcYPtZSHqp9oY63NQXT55YLpUU=
  - d: ldc
    os: linux
  - d: dmd
    os: osx

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: LqFD1B3h4b2RYlGW8fatBPdbzqOM03mteXKPQNOghrcGStDuDtDc+3h5xmfcPdgtkKML7RTJwrnBHTyvLIWuBMQV3rfFWX24zqo9pr+RDGw6NHSEmEjYdPhvXYDTc+/q6Cnz5JNAVeAoQ3w1Kc/RdCmSWsBgDMcTmkYi6KM/nfc=
    file: 
      - "plotcli-linux-gtk.tar.gz"
      - "plotcli-linux.tar.gz"
    on:
      tags: true
      repo: BlackEdder/plotd
      condition: "$TRAVIS_OS_NAME == linux && $DC == ldc2"
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: LqFD1B3h4b2RYlGW8fatBPdbzqOM03mteXKPQNOghrcGStDuDtDc+3h5xmfcPdgtkKML7RTJwrnBHTyvLIWuBMQV3rfFWX24zqo9pr+RDGw6NHSEmEjYdPhvXYDTc+/q6Cnz5JNAVeAoQ3w1Kc/RdCmSWsBgDMcTmkYi6KM/nfc=
    file: 
      - "plotcli-osx-gtk.tar.gz"
      - "plotcli-osx.tar.gz"
    on:
      tags: true
      repo: BlackEdder/plotd
      condition: "$TRAVIS_OS_NAME == osx"
